require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-airbnb

inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
