default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: itbt_development

test:
  <<: *default
  database: itbt_test

staging:
  <<: *default
  database: itbt_staging

production:
  <<: *default
  database: itbt_production
